### ISSUE TITLE
1.1.7.1: Error loading configuration in data.db

### ISSUE THREAD

**Issue by blockswerker** [UltimateGamer200/UltraColor#17]
This appeared in the UltraColor error file, after the console generated an exception that alerted me to the problem. Are there steps I should take to clear the error?

`More Information: 
Error loading configuration in data.db!
Problematic section: 6ce2b266-3164-4617-be12-6f3338c9eee8
Problem: java.util.ConcurrentModificationException (see below for more)
ConcurrentModificationException (Unknown cause)
	 at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:758)
	 at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:790)
	 at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:788)
	 at org.bukkit.configuration.MemorySection.mapChildrenValues(MemorySection.java:880)
	 at org.bukkit.configuration.MemorySection.getValues(MemorySection.java:107)
	 at UltraColor-1.4.4.jar//me.ultimategamer200.ultracolor.ultracolor.lib.settings.YamlConfig.getT(YamlConfig.java:550)
	 at UltraColor-1.4.4.jar//me.ultimategamer200.ultracolor.ultracolor.lib.settings.YamlConfig.getObject(YamlConfig.java:668)
	 at UltraColor-1.4.4.jar//me.ultimategamer200.ultracolor.ultracolor.lib.settings.YamlConfig.getString(YamlConfig.java:731)
	 at UltraColor-1.4.4.jar//me.ultimategamer200.ultracolor.PlayerCache.onLoadFinish(PlayerCache.java:48)
	 at UltraColor-1.4.4.jar//me.ultimategamer200.ultracolor.ultracolor.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:331)
	 at UltraColor-1.4.4.jar//me.ultimategamer200.ultracolor.PlayerCache.<init>(PlayerCache.java:43)
	 at UltraColor-1.4.4.jar//me.ultimategamer200.ultracolor.PlayerCache.getCache(PlayerCache.java:148)
	 at UltraColor-1.4.4.jar//me.ultimategamer200.ultracolor.DataFile.getCaches(DataFile.java:30)
	 at UltraColor-1.4.4.jar//me.ultimategamer200.ultracolor.listeners.PlayerListener.replaceNickWithPlayerInCommand(PlayerListener.java:67)
	 at UltraColor-1.4.4.jar//me.ultimategamer200.ultracolor.listeners.PlayerListener.lambda$onConsoleCommandSend$4(PlayerListener.java:60)
	 at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
	 at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	 at java.base/java.lang.Thread.run(Thread.java:831)
`

**Comment by UltimateGamer200** [comment]
Hello!

This is more of a coding-side exception, so it's nothing your side has caused (you can google more about this if you want, but basically, this usually occurs if a list that's being iterated on is modified during the iteration process). Another user has already reported this to me on the discord and it seems to be fixed.

I'll give you the test jar I gave him today and you can use that for now until a new update is posted on Spigot!

[Test Jar Here](https://ufile.io/1xi5gr7r)
